r"""执行日志分析：找换手率异常高的根因。"""
import pandas as pd

ex = pd.read_csv(r"project2_pairs\reports\pair_exec_v5.csv", encoding="utf-8-sig")
ex["date"] = pd.to_datetime(ex["date"])
print("执行笔数:", len(ex))
print("买入总额:", ex[ex["side"] == "buy"]["amount"].sum().round(3))
print("卖出总额:", ex[ex["side"] == "sell"]["amount"].sum().round(3))
print("费用总额:", ex["fee"].sum().round(4))
print()
print("== 按年 ==")
g = ex.groupby(ex["date"].dt.year)
print(g["amount"].sum().round(2).to_string())
print()
print("== 每只股票执行次数与总额 ==")
per = ex.groupby("code").agg(n=("amount", "count"), tot=("amount", "sum")).sort_values("tot", ascending=False)
print(per.head(12).to_string())
print()
print("== 调仓日数量 ==")
print("唯一调仓日:", ex["date"].nunique())
print()
print("== 单日执行额 top10（调仓日）==")
d = ex.groupby("date")["amount"].sum().sort_values(ascending=False)
print(d.head(10).to_string())
print()
print("== 最近 30 个调仓日 ==")
print(d.tail(30).to_string())
